### ISSUE TITLE
Documentation is sucks !

### ISSUE THREAD

**Issue by MRezaSafari** [kahanu/System.Linq.Dynamic#102]
Hello sir!

have you ever see the wiki pages by your self?

look this mess https://github.com/kahanu/System.Linq.Dynamic/wiki/LINQ-Project-Overview

**Comment by ryanvgates** [comment]
I'd like to add some context to this conversation. I was in the process of converting the documentation into markdown from it's original word format. I thought this would help make it more accessible. Unfortunately it turned out to be a non-trivial task and other professional/personal priorities came up. I agree that it could be better.
